app:
  datasource:
      jdbc-url: jdbc:postgresql://postgresqldb:5432/stoom
      username: postgres
      password: 1234
      pool-size: 30

server:
    error:
      include-message: always
      include-binding-errors: always

spring:
  flyway:
    baseline-on-migrate: true
